### ISSUE TITLE
[ORG] Setup modular label range

### ISSUE THREAD

**Issue by AdrieanKhisbe** [senecajs/q-and-a#4]
modular and composable _vim_ styles :wink:

**Comment by mcdonnelldean** [comment]
For now I think we have enough labels,

add-to-site-faq - I want to add this to senecajs.org
non-question - for things that aren't questions
answered - for when you think you have answered

I'd be wary about over labeling because you are going to get so much variance in terms of questions that it just won't scale.

**Comment by AdrieanKhisbe** [comment]
At last, adding the `meta` and `pending` one

**Comment by AdrieanKhisbe** [comment]
@mcdonnelldean , to be sure: 
`non-question` shouldn't be to flag irrelevant issues?

hence all the #2 #5 and #4 should be [meta](https://github.com/senecajs/q-and-a/labels/META)

**Comment by mcdonnelldean** [comment]
On this repo specifically I don't see why you need anything more that `this is a question`, `this is not a question`, 'this is a really good question we should take note'.

**Comment by naomifeehan** [comment]
@AdrieanKhisbe what does label "pending" indicate, that the question is being reviewed?

**Comment by mcdonnelldean** [comment]
Not sure for pending, can we remove? If this is for Q and A anything that isn't answered is pending. I'm not going to assign items when I start to answer, that is too much work.

On meta vs non-question, I don't like either :D I wonder maybe just org? Like how we do in senecajs.org?
